gl_platform_homepage:
    path:     /
    defaults: { _controller: GLPlatformBundle:Default:index }
    
    # src/OC/PlatformBundle/Resources/config/routing.yml

hello_the_world:
    path:     /hello-world
    defaults: { _controller: GLPlatformBundle:Advert:index }
